language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer install --no-dev --verbose

branches:
  only:
    - master

script:
  - phpunit --coverage-text

